dist: trusty
language: node_js
services:
  - docker
sudo: false
node_js: 
  - "node"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - ./node_modules
before_script:
  - npm install -g @angular/cli
install:
  - npm install
stages:
  - name: linter
    if: branch = master
  - name: unit-tests
    if: branch = master
  - name: e2e
    if: branch = master
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: linter
      script: npm run lint
    - stage: unit-tests
      script: bash ./ci/unit-tests
    - stage: e2e
      script: bash ./ci/e2e
    - stage: deploy
      script: bash ./ci/deploy && bash ./ci/release