version: 2
jobs:
  linter:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install local dependencies
          command: npm install

      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Building
          command: npm run lint
     
  # deploy:
  #   docker:
  #     - image: circleci/node:10

  #   working_directory: ~/repo

  #   steps:
  #     - checkout

  #     - run:
  #         name: Show current branch
  #         command: echo ${CIRCLE_BRANCH}

  #     - run:
  #         name: Deploy Docker Image
  #         command: bash ./ci/deploy

  #     - run:
  #         name: Deploy to Firebase
  #         command: bash ./ci/release
            

workflows:
  version: 2
  boolean-pipeline:
    jobs:
      - linter
      # - unit-tests
      # - e2e
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only:
      #           - master
