version: 2

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore Npm Package Cache
      keys:
        - v1-dependencies-{{ checksum "package.json" }}

  save_cache: &save_cache
    save_cache:
      name: Save NPM modules cache
      paths:
        - ~/.npm
        - ~/.cache
      key: v1-dependencies-{{ checksum "package.json" }}
  
  store_dist: &store_dist
    save_cache:
      name: Save dist folder
      paths:
        - dist
      key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
  
  restore_dist: &restore_dist
    restore_cache:
      name: Restore built dist folder
      keys:
        - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

  install_node_modules: &install_node_modules
    run:
      name: Install local dependencies
      command: npm ci

  show_current_branch: &show_current_branch
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}

jobs:
  linter:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *show_current_branch
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Linting
          command: npm run lint

  unit-tests:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *show_current_branch
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Running unit tests
          command: ./ci/unit-tests

  e2e:
    docker:
      - image: cypress/base:10
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *show_current_branch
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Running e2e tests
          command: bash ./ci/e2e

  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *show_current_branch
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Building artifact using ng build
          command: ./ci/build
      - <<: *store_dist

  staging-deploy:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *show_current_branch
      - <<: *restore_dist
      - run:
          name: Deploy Docker Image
          command: ./ci/deploy
      - run:
          name: Deploy to Heroku
          command: ./ci/release

  smoke-test-staging:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *show_current_branch
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Install Super Agent for smoke test
          command: npm i superagent
      - run:
          name: Running Smoke test
          command: ./ci/smoke-test

  production-deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *show_current_branch
      - <<: *restore_dist
      - run:
          name: Deploy Docker Image
          command: ./ci/deploy --prod
      - run:
          name: Deploy to Heroku
          command: ./ci/release --prod

workflows:
  version: 2
  angular-chile-pipeline:
    jobs:
      - linter
      - unit-tests
      - e2e
      - build:
          requires:
            - linter
            - unit-tests
            - e2e
      - staging-deploy:
          requires:
            - build
      - smoke-test-staging:
          requires:
            - staging-deploy
      - production-approval:
          type: approval
          requires:
            - smoke-test-staging
          filters:
            branches:
              only:
                - master
      - production-deploy:
          requires:
            - production-approval
          filters:
            branches:
              only:
                - master
